import {Platform, StyleSheet} from 'react-native';
import config from '../../config';
import {getStatusBarHeight} from '../../Util/Utilities';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  bannerImg: {
    width: config.Constant.SCREEN_WIDTH,
    height: config.Constant.SCREEN_HEIGHT / 2,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  bottomView: {
    width: config.Constant.SCREEN_WIDTH,
    backgroundColor: 'white',
    borderTopRightRadius: 35,
    borderTopLeftRadius: 35,
    paddingTop: 0,
    alignItems: 'center',
  },
  bottomScrollView: {
    width: config.Constant.SCREEN_WIDTH,
    backgroundColor: config.Constant.COLOR_TRANSPARENT,
    marginTop: 20,
  },
  titleTxt: {
    textAlign: 'center',
    fontSize: 27,
    fontFamily: config.Constant.Font_Bold,
    marginTop: 20,
    marginBottom: 65.52,
    color: config.Constant.COLOR_BLACK,
  },
  menuIconContainer: {
    zIndex: 10,
    width: config.Constant.SCREEN_WIDTH * 0.26,
    height: config.Constant.SCREEN_WIDTH * 0.26,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  menuIcon: {
    top: 0,
    left: 0,
    width: config.Constant.SCREEN_WIDTH * 0.26,
    height: config.Constant.SCREEN_WIDTH * 0.26,
    justifyContent: 'center',
    alignContent: 'center',
  },
  menuView: {
    opacity: 0.95,
    justifyContent: 'center',
    alignContent: 'center',
    paddingBottom: 20,
    marginTop: -10,
    marginHorizontal: -20,
  },
  iconImg: {
    width: 60,
    height: 60,
    marginLeft: 20,
    marginTop: 10,
    tintColor: config.Constant.COLOR_WHITE,
  },
  menuIconImg: {
    width: 60,
    height: 60,
    alignSelf: 'center',
    marginTop: 50,
    zIndex: 3,
    tintColor: config.Constant.COLOR_WHITE,
  },
  logoutIconImg: {
    width: 40,
    height: 40,
    alignSelf: 'center',
    marginTop: 40,
    marginBottom: 10,
    zIndex: 3,
    tintColor: config.Constant.COLOR_WHITE,
    transform: [{rotate: '180deg'}],
  },
  menuOptionView: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  menuTitleTxt: {
    fontFamily: config.Constant.Font_Semi_Bold,
    fontSize: 22,
    color: config.Constant.COLOR_WHITE,
  },
  searchBar: {
    width: '90%',
    padding: 10,
    backgroundColor: config.Constant.COLOR_INPUT,
    marginTop:
      config.Constant.SCREEN_HEIGHT * 0.2 + config.Constant.SCREEN_WIDTH * 0.26,
    alignSelf: 'center',
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIcon: {
    width: 20,
    height: 20,
    tintColor: config.Constant.COLOR_GREY,
    marginHorizontal: 10,
  },
  inputStyle: {
    padding: 0,
    flex: 1,
    textAlign: config.Constant.isRTL ? 'right' : 'left',
  },
  rowViewStyle: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '90%',
    paddingTop: 25,
    paddingBottom: 15,
    alignSelf: 'center',
    alignItems: 'flex-start',
  },
  rowTitle: {
    fontFamily: config.Constant.Font_Semi_Bold,
    fontSize: 20,
    color: config.Constant.COLOR_BLACK,
    //fontWeight: '600',
    flex: 1,
    letterSpacing: 1.4,
    textAlign: 'left',
  },
  rowBtnTitle: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 14,
    color: config.Constant.COLOR_LIGHT_GREY,
    letterSpacing: 1,
    marginTop: 4,
  },
  serviceView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  packageView: {
    width: config.Constant.SCREEN_WIDTH * 0.75,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 2,
    borderColor: config.Constant.COLOR_ULTRA_LIGHT_GREY,
  },
  userView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderRadius: 100,
    width: 70,
    height: 70,
    borderWidth: 0.5,
    borderColor: config.Constant.COLOR_BTN,
  },
  serviceImgView: {
    backgroundColor: '#711CD3',
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 5,
  },
  serviceName: {
    fontFamily: config.Constant.Font_LIGHT,
    fontSize: 15,
    color: config.Constant.COLOR_BLACK,
  },
  dresserRowViewStyle: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
    marginTop: 5,
  },
  dresserName: {
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 1,
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 10,
    textAlign: 'left',
  },
  startView: {
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_YELLOW,
    letterSpacing: 1,
    fontSize: 14,
    marginLeft: 5,
    marginBottom: Platform.OS == 'ios' ? 0 : -2,
  },
  reviewView: {
    fontFamily: config.Constant.Font_LIGHT,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 1,
    fontSize: 14,
    marginHorizontal: 5,
    marginBottom: Platform.OS == 'ios' ? 0 : -2,
  },
  kgView: {
    fontFamily: config.Constant.Font_LIGHT,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 1,
    fontSize: 14,
    flex: 1,
    paddingHorizontal: 10,
    marginTop: -2,
    textAlign: 'left',
  },
  btnView: {
    backgroundColor: config.Constant.COLOR_TAB,
    paddingVertical: 5,
    paddingHorizontal: 8,
    fontFamily: config.Constant.Font_Bold,
    color: config.Constant.COLOR_WHITE,
    letterSpacing: 1,
    fontSize: 15,
  },
  dialogStyle: {
    backgroundColor: config.Constant.COLOR_TRANSPARENT,
    borderRadius: 0,
    maxHeight: config.Constant.SCREEN_HEIGHT * 0.95,
    paddingTop: 10,
  },
  dialogContent: {
    backgroundColor: config.Constant.COLOR_TRANSPARENT,
    width: config.Constant.SCREEN_WIDTH,
    alignSelf: 'center',
    paddingBottom: 0,
    shadowColor: config.Constant.COLOR_GREY,
    shadowOffset: {
      width: 1,
      height: 1,
    },
    height: config.Constant.SCREEN_HEIGHT * 0.75,
    shadowRadius: 10,
    shadowOpacity: 1,
    elevation: 12,
  },
});
