require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'hairdresser_customer' do
  rn_maps_path = '../node_modules/react-native-maps'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Analytics'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'



  target 'hairdresser_customerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
end

target 'hairdresser_customer-tvOS' do
  # Pods for hairdresser_customer-tvOS

  target 'hairdresser_customer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end