import Config from "react-native-config";
import Constant from './Constant';
const AUTH_HEADER =Config.AUTH_HEADER
export default {
  AUTH_HEADER: AUTH_HEADER,
  LOGIN_API: Constant.Base_Url + 'login',
  REGISTER_API: Constant.Base_Url + 'register',
  CHECK_EMAIL: Constant.Base_Url + 'check_email',
  FORGOT_PASS: Constant.Base_Url + 'forgot_password',
  FORGOT_PASS_OTP: Constant.Base_Url + 'forgot_password_otp',
  UPDATE_PROFILE: Constant.Base_Url + 'update_profile',
  CHANGE_PASSWORD: Constant.Base_Url + 'change_password',
  categoryList: Constant.Base_Url + 'category_list',
  GET_NEAR_BY_DRESSER: Constant.Base_Url + 'near_by_hairdressor_list',
  GET_NEAR_BY_DRESSER_DASHBOARD: Constant.Base_Url + 'near_by_hairdressor_list_dashboard',
  ORDER_REQUEST: Constant.Base_Url + 'order_request',
  RETRY_ORDER: Constant.Base_Url + 'order_retry',
  SETTING: Constant.Base_Url + 'settings',
  ORDER_TIMEOUT: Constant.Base_Url + 'order_timeout',
  ORDER_CANCEL: Constant.Base_Url + 'order_cancel',
  ORDER_DETAILS: Constant.Base_Url + 'order_detail',
  NOTIFICATION_LIST: Constant.Base_Url + 'notification_list',
  FAVORITE_DRESSER_LIST: Constant.Base_Url + 'user_favorite_list',
  ORDER_LIST: Constant.Base_Url + 'my_order_list',
  HAIRDRESSER_DETAILS: Constant.Base_Url + 'hairdressor_detail',
  APPLY_PROMOCODE: Constant.Base_Url + 'apply_promocode',
  GET_PROFILE: Constant.Base_Url + 'profile',
  USER_FAVORITE: Constant.Base_Url + 'user_favorite',
  GET_BANNER: Constant.Base_Url + 'banner_list',
  GET_PRIOUS_DRESSER: Constant.Base_Url + 'previously_hired_hairdresser_list',
  WALLET_DATA: Constant.Base_Url + 'wallet_list',
  GET_WITHDRAW: Constant.Base_Url + 'user_withdraw_request',
  GIVE_RATING: Constant.Base_Url + 'order_review',
  DISPUTE_ORDER: Constant.Base_Url + 'order_dispute',
  CHECK_ONGOING_ORDER: Constant.Base_Url + 'check_ongoing_order',
  ORDER_PAYMENT: Constant.Base_Url + 'order_payment',
  DELETE_ACCOUNT: Constant.Base_Url + 'delete_profile',
  ADD_MONEY: Constant.Base_Url + 'add_money', 
  CLEAR_NOTIFICATION_LIST: Constant.Base_Url + 'clear_notification_list',
};
