export default {
  app:`customer`,
  welcomeBack: `Welcome Back`,
  loginToAcc: `Login to your account`,
  email: `Email`,
  password: `Password`,
  login: `Login`,
  forgotYourPass: `Forgot your password?`,
  dontHavAcc: `Don't have an account?`,
  signUp: `Sign Up`,
  signIn: `Sign In`,
  createAccount: `Create Account`,
  registerNewAccount: `Register new account`,
  alreadyHaveAc: `Already have an account?`,
  name: `Name`,
  emailAddress: `Email address`,
  phoneNumber: `Phone number`,
  confirmPassword: `Confirm password`,
  referrerNumber: `Referrer phone number`,
  otpHasSendToemail: `OTP has been sent to your email id and phone number.`,
  otpIsSendToemail: `OTP is sent to your email id and phone number.`,
  otpSendTitle: `OTP has been sent.`,
  enterOtp: `Enter OTP`,
  resend: `Resend`,
  submit: `Submit`,
  forgotPass: `Forgot Password`,
  enterYourEmail: `Please enter your registered email address.`,
  resetPass: `Reset Password`,
  back: `Back`,
  createNewPass: `Create New Password`,
  enterNewPass: `Enter new password`,
  newPass: `New Password`,
  confirmPass: `Confirm Password`,
  create: `Create`,
  myorders: `My Orders`,
  wallet: 'Wallet',
  support: `Support`,
  SwitchToArabic: `Switch to Arabic`,
  SwitchToEnglish: `Switch to English`,
  logout: 'Logout',
  seachService: `Search services`,
  topService: `Top Services`,
  viewAll: `View all`,
  nearByHairDresser: `Near by Hair Dressers`,
  specialPackage: `Special Package & Offers`,
  previouslyHired: `Previously Hired`,
  hello: 'Hello',
  yourLocation: `Your location`,
  CHANGE: `CHANGE`,
  change: `Change`,
  services: `Services`,
  searchHairDresser: `Search Hair dresser`,
  notification: `Notifications`,
  wishlist: `Wishlist`,
  profile: `Profile`,
  phone: `Phone`,
  email: `Email`,
  location: `Location`,
  editProfile: `Edit Profile`,
  changePassword: `Change Password`,
  bookNow: `Book Now`,
  about: `About`,
  services: `Services`,
  reviews: `Reviews`,
  yourOrders: `Your Orders`,
  reviewOrders: `Review Order`,
  service: `Service`,
  qty: `Qty`,
  price: `Price`,
  SubTotal: `Sub-total`,
  fees: `Fees`,
  confirm: `Confirm`,
  call: `Call`,
  checkout: `Checkout`,
  address: `Address`,
  applyCoupon: `Apply Coupon`,
  apply: 'Apply',
  paymentMethod: `Payment Method`,
  enterCouponCode: `Enter Coupon code`,
  creditDebitCard: `Credit / Debit Card`,
  cashOnDelivery: `Cash on delivery`,
  orderProcessing: `Order Processing`,
  wallet: `Wallet`,
  addAmount: `Add Amount`,
  recentTransactions: `Recent Transactions`,
  BALANCE: `BALANCE`,
  loadMore: `Load more`,
  amountCredited: `Amount credited`,
  amountDebited: `Amount debited`,
  generalProfile: `General Profile`,
  requestSend: `Request sent`,
  waitFor: `Wait for`,
  noResponce: `No Response`,
  tryAnotherDresser: `Please try another hairdresser.`,
  selectAnotherDressser: `Select Another Hairdresser`,
  tryAgain: `Try again`,
  requestRejected: `Request Rejected`,
  oldPass: `Old Password`,
  weAreProcessing: `We are processing your order`,
  dresserOnWay: `Hairdresser on the way`,
  workInProgress: `Work in progress`,
  orderCompleted: `Order Completed`,
  amountPaidInCash: `Amount to be paid in cash.`,
  track: `Track`,
  save: `Save`,
  enterValidEmail: `Enter valid email address`,
  enterValidPass: `Password field is required`,
  cancel: `Cancel`,
  inProgress: 'In progress',
  away: 'away',
  Total: `Total`,
  enterValidName: `Enter valid name`,
  enterValidPhone: `Enter valid phone number`,
  enterValidRePass: `Confirm password is not matched with password`,
  enterValidRefNum: `Enter valid referrer phone number`,
  loading: 'Loading...',
  error: 'Error',
  no_internet_title: 'Internet Error',
  no_internet_msg: 'Please check your internet connection',
  success: 'Success',
  somethingWentWrong: `Something went wrong try again after sometime`,
  enterValidPassLong: `Please fill password at least 8 character long`,
  wrongOtp: `Otp is incorrect`,
  enterValidNewRePass: `Confirm password is not matched with new password`,
  enterValidOldPass: `Old Password field is required`,
  enterValidNewPass: `New Password field is required`,
  selectOption: 'Select option for image selection',
  fromGallery: 'From Gallery',
  fromCamera: 'From Camera',
  online: 'Online',
  pleaseSelectOneService: 'Please select at least one service',
  changeLocation: 'Change Location',
  fillValidAddress: 'Please fill the address',
  pinpointOnMap: 'Please select your location on map',
  selectLocation: 'Please select your location.',
  noNotification: 'There are no notifications.',
  noFavorites: 'You are not added any favorite haidresser yet.',
  noOrder: 'There are no orders.',
  noReviews: 'There are no reviews.',
  noDresserAvailable: 'There are no hairdresser available at your location.',
  locationError:
    'Location permission is required for the basic functionality of this app. Please allow location permission from setting to use this application.',
  fillPromo: 'Please fill the promocode',
  tax: 'Tax',
  promoCode: 'Coupon Code',
  withdrawAmount: `Withdraw Amount`,
  offline: 'offline',
  reqestTimeot: 'Request Timeout',
  reqestCancel: 'Request Canceled',
  noWalletHistory: 'There are no transactions.',
  giveFeedback: 'Give Feedback',
  postExperience: 'Post your experience',
  dispute: `Dispute`,
  explainIssue: `Kindly explain your issue.`,
  add_someting_about_you: 'Add someting about you',
  pleaseAddYouReview: 'Please add review',
  add_Services: 'There are no services',
  cancelOrder: `Cancel Order`,
  hideMap: 'Hide Map',
  showMap: 'Show Map',
  PayToStartOrder: 'Pay To Start Order',
  PendingWallet: 'Pending Wallet',
  deleteAccount: "Delete Account",
  deleteAccountMsg: "Are you sure you want to delete your account?",
  No: "No",
  Yes: "Yes",
  Done: "Done",
  PaymentAlertHeader: "Payment",
  PaymentAlertDesc: "Do you want to use wallet balance?",
  PaymentAlertDesc2: "Do you want to do Payment?",
  NoServiceFound: "No Service Found",
  paymentReqestTimeot: 'Payment Request Timeout',
  ok: 'Ok',
  minCash: 'Order minimum limit',
  maxCash: 'Cash maximum limit',
  subtotalNeedToMoreThenMinimumCashAmount: 'Subtotal need to more then minimum cash amount.',
  bankAccNum: 'Bank Account Number',
  AddService: 'Add Service',
  DoYouWantToCancelServiceRequest:'Do you want to cancel service request?',
  DueAmount:'Due Amount',
  agree:`Agree `,
  termsAndCondition: `Terms And Condition`,
  pleaseAgreeTermsAndConditions:`please agree terms and conditions`,
  clear_all:"Clear all",
  MAKEPAYMENT:"Make Payment",
  selectPaymentMethod:"Please select payment method",
  PaymentMethods: 'Payment Methods',
  ClickMethod: 'Click one of the methods',
  OsValid:'Please upgrade your IOS to 16.0 to support Apple Pay or use MADA option',
  paymentSuccess: 'Payment successfully!',
};