export default {
  app:`customer`,
  welcomeBack: `مرحبا بعودتك`,
  loginToAcc: `تسجيل الدخول إلى حسابك`,
  email: `البريد الالكتروني`,
  password: `كلمة المرور`,
  login: `تسجيل الدخول`,
  forgotYourPass: `نسيت كلمة المرور؟`,
  dontHavAcc: `ليس لديك حساب؟`,
  signUp: `تسجيل`,
  signIn: `تسجيل الدخول`,
  createAccount: `انشئ حساب جديد`,
  registerNewAccount: `تسجيل حساب جديد`,
  alreadyHaveAc: `هل لديك حساب؟`,
  name: `الاسم`,
  emailAddress: `البريد الالكتروني`,
  phoneNumber: `رقم الهاتف`,
  confirmPassword: `تأكيد كلمة المرور`,
  referrerNumber: `رقم الهاتف المُحيل`,
  otpHasSendToemail: `تم إرسال رمز التفعيل الى بريدك الالكتروني ورقم الهاتف الخاص بك`,
  otpIsSendToemail: `تم إرسال رمز التفعيل الى بريدك الالكتروني ورقم الهاتف الخاص بك`,
  otpSendTitle: `تم إرسال رمز التفعيل`,
  enterOtp: `إدخال رمز التفعيل`,
  resend: `إعادة الارسال`,
  submit: `تأكيد`,
  forgotPass: `نسيت كلمة المرور`,
  enterYourEmail: `الرجاء إدخال عنوان بريدك الإلكتروني المسجل`,
  resetPass: `إعادة تعيين كلمة المرور`,
  back: `العودة الى الخلف`,
  createNewPass: `إنشاء كلمة مرور جديدة`,
  enterNewPass: `ادخل كلمة مرور جديدة`,
  newPass: `كلمة مرور جديدة`,
  confirmPass: `تأكيد كلمة المرور`,
  create: `إنشاء`,
  myorders: `طلباتي`,
  wallet: 'المحفظة',
  support: `الدعم الفني`,
  SwitchToArabic: `التغيير الى اللغة العربية`,
  SwitchToEnglish: `التغيير الى اللغة الانقليزية`,
  logout: 'تسجيل الخروج',
  seachService: `البحث عن خدمة`,
  topService: `افضل الخدمات`,
  viewAll: `عرض الكل`,
  nearByHairDresser: `المصففين القريبين منك`,
  specialPackage: `الباقات والعروض الخاصة`,
  previouslyHired: `تم تعيينه مسبقًا`,
  hello: 'مرحبًا',
  yourLocation: `موقعك الحالي`,
  CHANGE: `تغيير`,
  change: `تغيير`,
  services: `الخدمات`,
  searchHairDresser: `البحث عن مصففة شعر`,
  notification: `الإشعارات`,
  wishlist: `قائمة المفضلة`,
  profile: `الحساب الشخصي`,
  phone: `رقم الهاتف`,
  email: `البريد الالكتروني`,
  location: `الموقع`,
  editProfile: `تعديل الحساب الشخصي`,
  changePassword: `تغيير كلمة المرور`,
  bookNow: `الحجز الان`,
  about: `عن`,
  services: `الخدمات`,
  reviews: `التقييمات`,
  yourOrders: `الطلبات الخاصة بك`,
  reviewOrders: `مراجعة الطلب`,
  service: `الخدمات`,
  qty: `الكمية`,
  price: `السعر`,
  SubTotal: `المجموع`,
  fees: `الرسوم`,
  confirm: `تأكيد`,
  call: `اتصال`,
  checkout: `الدفع`,
  address: `العنوان`,
  applyCoupon: `إضافة كود خصم`,
  apply: 'تفعيل',
  paymentMethod: `وسيلة الدفع`,
  enterCouponCode: `أدخل رمز كود الخصم`,
  creditDebitCard:`الدفع الالكتروني`,// creditDebitCard: `بطاقة الائتمان`,
  cashOnDelivery: `الدفع نقدًا`,
  orderProcessing: `معالجة الطلب`,
  wallet: `المحفظة`,
  addAmount: `أضف المبلغ`,
  recentTransactions: `العمليات السابقة`,
  BALANCE: `رصيد حساب`,
  loadMore: `تحميل المزيد`,
  amountCredited: `المبلغ المضاف`,
  amountDebited: `المبلغ المخصوم`,
  generalProfile: `الحساب العام`,
  requestSend: `تم ارسال الطلب`,
  waitFor: `أنتظر لأجل`,
  noResponce: `لا يوجد رد`,
  tryAnotherDresser: `الرجاء اختيار اخصائية اخرى.`,
  selectAnotherDressser: `اختر اخصائية اخرى`,
  tryAgain: `حاول مرة اخرى`,
  requestRejected: `تم رفض الطلب`,
  oldPass: `كلمة المرور القديمة`,
  weAreProcessing: `جاري معالجة العملية `,
  dresserOnWay: `الاخصائية في الطريق`,
  workInProgress: `العمل قيد التنفيذ`,
  orderCompleted: `تم تنفيذ الطلب`,
  amountPaidInCash: `المبلغ الواجب دفعه نقدا`,
  track: `تتبع`,
  save: `حفظ`,
  cancel: `إلغاء`,
  inProgress: 'جاري العمل',
  away: 'بعيدا',
  Total: `الاجمالي`,
  enterValidName: `ادخل اسم صالح`,
  enterValidPhone: `ادخل رقم هاتف صالح`,
  enterValidRePass: `تأكيد كلمة المرور لا يتطابق مع كلمة المرور`,
  enterValidRefNum: `ادخل رقم هاتف صالح`,
  loading: 'يرجى الانتظار...',
  error: 'حدث خطا ما',
  no_internet_title: 'خطا في الاتصال بالشبكة',
  no_internet_msg: 'يرجى التحقق من اتصالك بالشبكة',
  success: 'نجحت العملية',
  somethingWentWrong: `حدث خطا ما يرجى معاودة المحاولة لاحقا`,
  enterValidPassLong: `يجب ان تحتوي كلمة المرور على الاقل 8 حروف `,
  wrongOtp: `رمز التفعيل خاطئ`,
  enterValidNewRePass: `تأكيد كلمة المرور لايطابق كلمة المرور الفعلية`,
  enterValidOldPass: `كلمة المرور السابقة مطلوبة`,
  enterValidNewPass: `كلمة المرور الجديدة مطلوب`,
  selectOption: 'حدد الخيار لاختيار الصورة',
  fromGallery: 'من معرض الصور',
  fromCamera: 'التقاط صورة ',
  online: 'متصل',
  pleaseSelectOneService: 'الرجاء تحديد خدمة واحدة على الأقل',
  changeLocation: 'تغيير الموقع',
  fillValidAddress: 'يرجى ملء العنوان',
  pinpointOnMap: 'الرجاء تحديد موقعك على الخريطة',
  selectLocation: 'الرجاء تحديد موقعك',
  noNotification: 'لاتوجد اي اشعارات',
  noFavorites: 'لم تتم إضافة اي اخصائية حتى الان',
  noOrder: 'لاتوجد طلبات',
  noReviews: 'لاتوجد تقييمات',
  noDresserAvailable: 'لاتوجد اخصائية متوفرة في موقعك',
  locationError: 'يرجى السماح بإذن الموقع من الإعداد لاستخدام هذا التطبيق.',
  fillPromo: 'يرجى ملء الرمز الترويجي',
  tax: 'شامل الضريبه وقيمتها ',
  promoCode: 'رمز الكوبون',
  withdrawAmount: `سحب المبلغ`,
  offline: 'غير متصل',
  dispute: `اعتراض`,
  explainIssue: `يرجى شرح مشكلتك.`,
  giveFeedback: 'التقييم',
  postExperience: 'اضف تجربتك',
  reqestTimeot: 'طلب مهلة',
  reqestCancel: 'تم إلغاء الطلب',
  withdrawAmount: `سحب المبلغ`,
  noWalletHistory: 'لا يوجد تقييمات.',
  add_someting_about_you: 'اضف شيء عنك',
  pleaseAddYouReview: 'يرجى إضافة مراجعة ',
  add_Services: 'لاتوجد خدمة',
  hideMap: 'إخفاء الخريطة',
  showMap: 'عرض الخريطة',
  cancelOrder: `الغاء الطلب`,
  PayToStartOrder: 'ادفع لبدء الطلب',
  PendingWallet: 'بإنتظار الدفع',
  deleteAccount: "حذف الحساب",
  deleteAccountMsg: "هل انت متأكد انك تريد حذف حسابك؟",
  No: "لا",
  Yes: "نعم",
  Done: 'تم',
  PaymentAlertHeader: "اشعار دفع",
  PaymentAlertDesc: "لديك رصيد في المحفظة هل ترغب في استخدامة؟",
  PaymentAlertDesc2: "هل  ترغب في الدفع الان؟",
  NoServiceFound: "لايوجد خدمات",
  paymentReqestTimeot: 'انتهت مهلة الدفع',
  ok: 'نعم',
  minCash: 'الحد الادنى للطلب',
  maxCash: 'الحد الأعلى للدفع النقدي',
  subtotalNeedToMoreThenMinimumCashAmount: 'انت بحاجه إلى أكثر من الحد الأدنى للمبلغ النقدي.',
  bankAccNum: 'رقم الحساب / ايبان',
  AddService: 'اضافة خدمة',
  DoYouWantToCancelServiceRequest:'هل انت متاكد من رغبتك في إلغاء الخدمه؟',
  DueAmount:'مبلغ سابق',
  agree:`الموافقة `,
  termsAndCondition: `على شروط الاستخدام`,
  pleaseAgreeTermsAndConditions:`الرجاء الموافقة على شروط الاستخدام`,
  clear_all:"امسح الكل",
  PaymentMethods: 'طرق الدفع',
  ClickMethod: 'انقر فوق إحدى الطرق',
  MAKEPAYMENT:"قم بالدفع",
  selectPaymentMethod:"الرجاء تحديد طريقة الدفع",
  paymentSuccess: 'تم الدفع بنجاح!',

};
